# Generated by Django 5.2.7 on 2025-11-11 17:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Initiative', 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='visionmission',
            options={'verbose_name': 'Vision & Mission', 'verbose_name_plural': 'Vision & Mission'},
        ),
        migrations.RenameField(
            model_name='visionmission',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='initiative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1920x600px', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True, help_text='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(help_text='Recommended size: 600x400px', upload_to='initiatives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.BooleanField(default=True, help_text='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='label',
            field=models.CharField(help_text='e.g., Rescues Monthly', max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='status',
            field=models.BooleanField(default=True, help_text='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.CharField(help_text='e.g., 500+', max_length=50),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=200),
        ),
    ]
